### ISSUE TITLE
cmd cannot be "cd"

### ISSUE THREAD

**Issue by spall** [ndmitchell/rattle#5]
It seems that 'cmd "cd"' doesn't work.    It produces an error like this:

> rattle-test: user error (Development.Shake.cmd, system command failed
> Command line: fsatrace rwmdqt /tmp/extra-dir-9274181680790/fsatrace.txt -- cd
> Original command line: cd
> Exit code: 1
> Stderr:
> )

This seems like a bug to me.

**Comment by spall** [comment]
I am realizing that the intention is probably to not allow this as the user should use  "setCurrentDirectory" so I am going to close this issue.

**Comment by ndmitchell** [comment]
Uses definitely shouldn't use setCurrentDirectory - that is likely to break everything! Instead users should use `cmd (Cwd pathIWant) myCommand` - which I pushed support for earlier today.

**Comment by spall** [comment]
Oh great! Thanks! Does this let the build change directories and then all subsequent commands occur in that directory?

**Comment by ndmitchell** [comment]
Nope, it's stateless - it applies to that `cmd` alone - you have to include it on every command. Having a `withCwd` to Rattle that added it to all inner commands would be possible. It's important not to change the directory in any multithreaded process since it's a system wide state. In Shake if you have `--lint` turned on then it periodically checks the current directory and throws an error if it sees it has been changed.

**Comment by spall** [comment]
Okay; I think adding a withCmd will be a good idea.  I can probably work on that.

**Comment by ndmitchell** [comment]
I just pushed a patch adding withCmdOptions of the type described in another message. Using that:

```
withCmdOptions [Cwd "whatever"] $ do
   cmd ...
   cmd ...
```

And it will be equivalent to adding `Cwd "whatever"` onto all the commands.
